### ISSUE TITLE
Trying to dynamically update model

### ISSUE THREAD

**Issue by xiz2020** [msqr1/Vosklet#11]
Hi. Latest version fixes error with memory. Now I'm trying to dynamically update model and language. Here is a code: 

`<!DOCTYPE html>
<html>
  <head>
    <script src="addCOI.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/msqr1/Vosklet@1.1.0/examples/Vosklet.min.js" async defer></script>

    
	
	<select id="languageSelect">
		<option value="">Select Please</option>
		<option value="en">English</option>
		<option value="ru">Russian</option>
	</select>

	    <script>

		let module
		let model
		let recognizer
		let transferer
		
		document.getElementById("languageSelect").addEventListener('change', (e) => {
			var lang = document.getElementById("languageSelect").value;
			
			console.log('Selected Lang:', lang);
			
			if (lang && lang.length) {
				if (module) {
					//try {
						
						module.cleanUp()
						
						//model 		= null
						//recognizer	= null
						//transferer  = null
						
					//} catch(e) {}
				}
				
				start(lang)
			}
		});
		
		async function start(lang) {
	
			let p; 
			if (lang == 'en') {
				p = 'https://vosk9/examples/vosk-model-small-en-us-0.15.tar.gz';
			} else if (lang == 'ru') {
				p = 'https://vosk9/examples/vosk-model-small-ru-0.4.tar.gz';
			} 
						
			let ctx = new AudioContext({sampleRate : 16000})
			let micNode = ctx.createMediaStreamSource(await navigator.mediaDevices.getUserMedia({
			  video: false,
			  audio: {
				echoCancellation: true,
				noiseSuppression: true,
				channelCount: 1,
				sampleRate: 16000
			  },
			}))

			module 		= await loadVosklet()
			model 		= await module.createModel(p,"model","ID")
			recognizer 	= await module.createRecognizer(model, 16000)

			recognizer.addEventListener("result", ev => {
				var data = JSON.parse(ev.detail)
				console.log("Result: ", data.text)
			})
			
			recognizer.addEventListener("partialResult", ev => {
				console.log("Partial result: ", ev.detail)
			})

			// Create a transferer node to get audio data on the main thread
			transferer = await module.createTransferer(ctx, 128 * 150)
			
			transferer.port.onmessage = ev => {
				recognizer.acceptWaveform(ev.data)
			}
			
			// Connect to microphone
			micNode.connect(transferer)
		}
    </script>
	
  </head>
</html>`

First language selection: 
![ru_Screenshot 2024-08-20 151740](https://github.com/user-attachments/assets/2618aa7f-92ec-40ab-a4b0-c34773e70196)
Next: trying to change our lang: 
![en_Screenshot 2024-08-20 152012](https://github.com/user-attachments/assets/fb10fe55-683f-474e-9d39-841fd908edf6)

Lang not changed. I see some slowness in work.  
All test was made in Chrome Incognito mode & Edge. Regular Chrome mode shows: Uncaught (in promise) Untar: Not a directory or regular file

**Comment by msqr1** [comment]
I'm sorry if this take long, I'm still figuring out what went wrong

**Comment by msqr1** [comment]
Basically, your line: ```await module.createModel(p,"model","ID")``` doesn't fetch the other russian model. This doesn't recognize the URL is different. It only will for id or name. If you want fast startup with both russian and english model on the client and just switch between folders, you can do ```await module.createModel(p, lang == "en" ? "en-model" : "ru-model","ID")```. Or if you want to re-fetch every time it change to save on storage space, you would do await module.createModel(p, "model",lang == "en" ? "en" : "ru")

**Comment by YuryKonvpalto** [comment]
If I call russian model in script (see below) it anyway takes en eng model.

<script src="https://cdn.jsdelivr.net/gh/msqr1/Vosklet@1.0.4/examples/Vosklet.min.js" async defer></script>
let module = await loadVosklet()
let model = await module.createModel("./vosk-model-small-ru-0.22.zip", "model", "ID")
let recognizer = await module.createRecognizer(model, 16000)

Even if leave it without path to model at all, it takes eng model:
let model = await module.createModel("./", "model", "ID")

Looks like the eng model is within Vosklet.min.js script and is always taken by default.
Any suggestion pls?

**Comment by msqr1** [comment]
First, please use the latest version, 1.1.1. Second, the model constructor overload models based on ID or storage path. 
If you want fast startup with both russian and english model on the client and just switch between folders, you can do ```await module.createModel(p, language == "en" ? "en-model" : "ru-model","ID")```. Or if you want to re-fetch every time it change to save on storage space, you would do ```await module.createModel(p, "model",language == "en" ? "en" : "ru")```
