### ISSUE TITLE
Default model within library?

### ISSUE THREAD

**Issue by YuryKonvpalto** [msqr1/Vosklet#12]
If I call russian model in script (see below) it anyway takes en eng model.

<script src="https://cdn.jsdelivr.net/gh/msqr1/Vosklet@1.0.4/examples/Vosklet.min.js" async defer></script>
let module = await loadVosklet()
let model = await module.createModel("./vosk-model-small-ru-0.22.zip", "model", "ID")
let recognizer = await module.createRecognizer(model, 16000)

Even if leave it without path to model at all, it takes eng model:
let model = await module.createModel("./", "model", "ID")

Looks like the eng model is within Vosklet.min.js script and is always taken by default.
Any suggestion pls?

**Comment by msqr1** [comment]
First, please use the latest version, 1.1.1. Second, the model constructor overload models based on ID or storage path, not URL.
If you want fast startup with both russian and english model on the client and just switch between folders, you can do ```await module.createModel(p, language == "en" ? "en-model" : "ru-model","ID")```. Or if you want to re-fetch every time it change to save on storage space, you would do ```await module.createModel(p, "model",language == "en" ? "en" : "ru")``` @YuryKonvpalto

**Comment by YuryKonvpalto** [comment]
Thanx a lot for a promt feedback.
Could ypu pls provide a link to ru .tar file on https://ccoreilly.github.io ?
 I'll try to follow your Example on https://github.com/msqr1/Vosklet/blob/main/Examples/fromWav.html with ru .tar.

**Comment by msqr1** [comment]
Look here to find what model you want: https://github.com/ccoreilly/vosk-browser/tree/master/examples%2Freact%2Fpublic%2Fmodels.
Choose one, and attach it to         ```https://ccoreilly.github.io/vosk-browser/models/``` for the URL

**Comment by YuryKonvpalto** [comment]
Thanks for link.
But it just doesnt work.:) Now it says "Untar: Incorrect tar format, must be USTAR". If I switch back to eng version (it worked just a minute ago) - it continues to throw error - "Untar: Incorrect tar format, must be USTAR".
I open my html with script in VSCode with LiveServer.

This is my tiny and simple code index.html. Try to start it with en-model and then with ru-model. In best case you would get en-model transcription anyway. Otherwise you will get some error:

<html>
<head>
  <script src="./Vosklet.js"></script> ///// I have loaded your lasr version from github and placed in my folder
  <script>
    async function start() {
    
      let ctx = new AudioContext({ sampleRate: 16000 })
      let module = await loadVosklet()
      let model = await module.createModel("https://ccoreilly.github.io/vosk-browser/models/vosk-model-small-en-us-0.15.tar.gz", "model", "ID")
      // let model = await module.createModel("https://ccoreilly.github.io/vosk-browser/models/vosk_model_small_ru_0_4_tar_gz", "model", "ID")
 
      let recognizer = await module.createRecognizer(model, 16000)

   
      recognizer.addEventListener("result", ev => {
        console.log("Result: ", ev.detail)
      })
      recognizer.addEventListener("partialResult", ev => {
        console.log("Partial result: ", ev.detail)
      })

   
      let wav = await fetch("./09_neutral_happiness n_010.wav")
      let audioBuf = await ctx.decodeAudioData(await wav.arrayBuffer())
      recognizer.acceptWaveform(audioBuf.getChannelData(0))
    }
  </script>
</head>
<button onclick="start()">Start</button>
</html>

**Comment by msqr1** [comment]
Again, change in URL doesn't update the stored model. You have to change ID or storepath. To assist you in managing this you should use the OPFS explorer extension. Also, the russian model URL looks kinda wrong?

**Comment by msqr1** [comment]
Again, change in URL doesn't update the stored model. You have to change ID or storepath. To assist you in managing this you should use the OPFS explorer extension. Also, the russian model URL looks kinda wrong?

**Comment by YuryKonvpalto** [comment]
> Again, change in URL doesn't update the stored model. You have to change ID or storepath. To assist you in managing this you should use the OPFS explorer extension. Also, the russian model URL looks kinda wrong?

Yes, russian model link is not correct, but I think it's not the case. I'll try to use OPFS, like you have suggested. I'll keep ypu informed if you are interested). Thanx for a tip again.

**Comment by YuryKonvpalto** [comment]
Yes, the Vosklet works! Thanks for pointing to OPFS - very usefull thing.
The models are outdated a bit though. Vosk has updated all the models on their website, but they are all in zip-format.
On the otherhand, yuor models are smaller.
Could you pls explain in few words a difference between partil result and result? Partial - it takes a chunk of audio?
And does Vosklet transcribe mp3?

**Comment by msqr1** [comment]
For the zip format, you kinda have to download and host it yourself in .tar.gz because I used ```DecompressionStream``` of the browser that only supports gzip. 

When silence is detected, a result is fired. That result won't change again. If silence is not detected (you're still talking), you will get a partial result that might change, especially the last word
