### ISSUE TITLE
How to convert some models from one format to another

### ISSUE THREAD

**Issue by xiz2020** [msqr1/Vosklet#14]
We have a lot of models here: https://alphacephei.com/vosk/models
All of them are in ZIP format. ZIP format is not supported by default vosklet script. 
When I'm trying to recode it to .tar.gz - nothing happens. 
What tool should I use to make accepted structure?

Thanks.

**Comment by msqr1** [comment]
You can unzip the model, then tar the top folder,  then gzip the tarball. In this case, though, you kinda have to host it yourself because there is no way for Vosklet to take in a .zip.
