### ISSUE TITLE
Load model locally

### ISSUE THREAD

**Issue by AhmedSawx** [msqr1/Vosklet#17]
Hi,
I'm making an app that uses [Tauri](https://github.com/tauri-apps/tauri), and I want to bundle the model with the application (since I want it to be offline). Are there ways to load the model locally?

**Comment by msqr1** [comment]
If I understand correctly, you need to loaf a local model, right?

**Comment by AhmedSawx** [comment]
Well, Tauri uses the system's browser to render the app, so I guess you can call it a 'web' app.
But it does run WASM.

Here, I put a test to see if WebAssembly works or not:
![webassembly test code](https://github.com/user-attachments/assets/ad5024f9-7ae9-43b1-9fd5-3d9624b8f956)


Here's the result:
![webassembly log](https://github.com/user-attachments/assets/e8d0ce6c-5fef-4840-85e8-a58db77a79ee)

So yes, it does support WASM. My question is whether there's a way to load the model instead of letting the user download it. if not, are there some ways to achieve that?

**Comment by msqr1** [comment]
In that case, you can download a model via a call to createModel with your selected URL, path, and id. 

This is the norm. I don't recall the user having to download the model themselves. A call to createModel with fetch and cache the model for you.

**Comment by AhmedSawx** [comment]
Okay. i did what you said.

But i got a problem, i'm getting this error:
`10-15 20:31:05.080  7532  7532 E Tauri/Console: File: http://tauri.localhost/js/Vosklet.js - Line 1 - Msg: Uncaught (in promise) DataCloneError: Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.`

i looked around and found out that CORS policy are [blocking tauri's localhost](https://stackoverflow.com/questions/76521778/tauri-app-api-request-blocked-by-cors-with-api-built-with-django-restframework). they said i should use it's http plugin. how can i edit `vosklet.js` to make it use tauri's http plugin?

**Comment by msqr1** [comment]
Can you somehow use that plugin to inject the COOP AND COEP headers into your app using that HTTP client?

**Comment by mehryar100** [comment]
hi msqr1 , 
I am  trying to add new language models to vosklet . How can I do that. BTW I am engaged in a linguistic project and need more assistance . Please contact at:
mehryar100@yahoo.de  to explain more about my  project .

**Comment by msqr1** [comment]
We can talk about that over in #18. It seemed off topic here.
