### ISSUE TITLE
evaluation give worse metrics then server-based VOSK. Way to run it sync for test?

### ISSUE THREAD

**Issue by korabelnikov** [msqr1/Vosklet#3]
I have a dataset of syllables on which I perform the evaluation.
Each wav = 1 syllable (0.2 sec). Just read one by one, recognize, check with ground true.

Vosk on the host gives ~80% accuracy.

Vosklet give ~65%, Possible it's because async nature of the js wrapper. 
I use a timeout 2 sec to divide different wav recognition, but 11% of records have nothing as recognized result, and 8% contains 2 syllables.

Other things all the same between hosted Vosk and browser Vosklet.
Maybe running in main thread synchronously will help?

**Comment by msqr1** [comment]
Running on the browser main thread on the  will block it, resulting in browser freeze. Are you sure everything is the same, like double-precision? I can still make you a synchronous wrapper if you want.

**Comment by msqr1** [comment]
What browser are you running it on?

**Comment by msqr1** [comment]
@korabelnikov I made a sync version, check the ```synchronous``` branch.

**Comment by tdcook** [comment]
I've noticed similar inaccuracies. I tried the synchronous version but I'm not seeing any `result` or `partialResult` events being fired.

**Comment by msqr1** [comment]
Hmm... I literally have no idea what is wrong? I need some help lol...

**Comment by tdcook** [comment]
I'd like to help out where I can, but the build process seems complex and I can't figure out how to build Kaldi and Vosk in ways that will make the `test` script run. Is there some documentation you could point me towards?

**Comment by msqr1** [comment]
For the test script, it just build the finished JS in whatever mode I use to test. It is the same as the make script, but the out filename is test.js, with manual decompression to test the tgz models locally

**Comment by korabelnikov** [comment]
sorry guys, we moved toward backend vosk recognition for a while. @tdcook Have you found something related?

**Comment by tdcook** [comment]
Hi @msqr1, I can verify that recognition is working as expected for me as of v1.2.0. Sorry for the late follow-up, I have been busy and haven't had much time to work on my project.
