### ISSUE TITLE
ReferenceError: Can't find variable: SharedArrayBuffer

### ISSUE THREAD

**Issue by jakespracher** [msqr1/Vosklet#4]
```
[Error] Unhandled Promise Rejection: ReferenceError: Can't find variable: SharedArrayBuffer
	(anonymous function) (Vosklet.js:9:9494)
	(anonymous function) (index.html:21)
```

Safari Version 17.3.1 (19617.2.4.11.12)

Happens after clicking start and speaking via the example

Thanks for the lib, still failing to get browser offline speech recognition working with any example from any offering 🙃

**Comment by msqr1** [comment]
You followed the fromMic.html, right? Can you screenshot the problem? I never get the issue before, I will try to reproduce it and see what can we do from there.

**Comment by msqr1** [comment]
I couldn't reproduce this on Chrome, Edge, or Firefox, maybe this is a Safari issue?

**Comment by cellis** [comment]
Same on Chrome

**Comment by cellis** [comment]
I think, per [this](https://stackoverflow.com/questions/64650119/react-error-sharedarraybuffer-is-not-defined-in-firefox), that we just need to send the correct headers from the server.

**Comment by jakespracher** [comment]
Ah interesting, adding those two headers makes the original error log go away and adds two more that are CSP related

```
[Error] Refused to load blob:http://localhost:4000/59684ac0-cdde-4534-9394-9499838d5deb because it does not appear in the worker-src directive of the Content Security Policy.
[Error] Unhandled Promise Rejection: SecurityError: The operation is insecure.
	(anonymous function) (app.js:9510)
```

**Comment by msqr1** [comment]
You may have a strict CSP for default-src or child-src (Safari and some other) that disallow blobs. Try setting worker-src to blob, let me know if it work!

**Comment by jakespracher** [comment]
I think we can close this one out due to the header requirements for SharedArrayBuffer and general CSP issues, though not sure if it'd be worth adding documentation about this. That said, it's still not working 😅 may open a separate issue.

**Comment by jakespracher** [comment]
Relevant docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements

**Comment by msqr1** [comment]
Does it work on other browser?

**Comment by msqr1** [comment]
> if it'd be worth adding documentation about this. 

Some docs on CSP testing would be nice, but we have to make yours work to confirm it. We already have docs for the response headers

**Comment by msqr1** [comment]
> That said, it's still not working 😅 may open a separate issue.

worker-src set to blob still doesn't work?

**Comment by jakespracher** [comment]
@cellis mentioned he encountered this on Chrome, it doesn't seem safari specific. Once I get the state of my local cleaned up I can revert the fix and try. I think worker-src blob does work but for now I've disabled my CSP and am still working around the failed to fetch issue in #1

**Comment by msqr1** [comment]
Can you review the proposal for fixing I have in #1?
