### ISSUE TITLE
"TypeError: cannot convert undefined to object" in VoskletTransferer

### ISSUE THREAD

**Issue by tdcook** [msqr1/Vosklet#7]
Sometimes, `VoskletTransferer` will throw a `TypeError: cannot convert undefined to object` exception immediately after initialization. It won't always happen right away, but usually will after a few reloads. It seems there is a race condition between the connection of the source and processor nodes and the execution of `VoskletTransferer`'s `process` method.

The error is being thrown here:

https://github.com/msqr1/Vosklet/blob/76aedbdfee862de8a734a3a4f09ffb82eeaf50da/src/wrapper.js#L11

Adding a falsiness check here should fix it:

```javascript
const data = inputs[0][0]
if (!data) return true
this.buffer.set(data, this.count * 128)
```

**Comment by msqr1** [comment]
Ngl, I never encounter this issue when i test. Thanks for pointing this out, I'll fix it ASAP!

**Comment by tdcook** [comment]
I have tried Chrome and Firefox, all on a Linux machine with a USB microphone attached. I suspect it only crops up on certain systems.

**Comment by msqr1** [comment]
Can you try unplugging the USB microphone?

**Comment by tdcook** [comment]
It happens right on startup, before any recognition starts. I have only seen it happen there, never after a successful startup.

**Comment by msqr1** [comment]
This path of code is quite hot, can you try unplugging the USB microphone to see? I tried many times to see if it would pop up, but it wouldn't. Can you try if the USB microphone was the problem? Maybe it messed with the AudioContext?

**Comment by tdcook** [comment]
Well, if I remove the USB microphone from that machine, I won't have any microphone input to use. Instead I tested it on two laptops using their built-in microphones:

Framework Laptop 16 (Fedora Linux 40): Firefox 126 repros inconsistently. Chrome 125 repros more consistently but occasionally works.

Surface Pro 4 (Windows 10): Firefox 126 repros inconsistently. Edge reproed once on the very first try but never reproed again.

According to [the spec](https://webaudio.github.io/web-audio-api/#audioworkletprocess-callback-parameters) the inputs array for a source can be empty if the source node is not "actively processing". Perhaps there is, on some OS/browser combinations, a moment after initialization where the microphone stream node is not actively processing.

**Comment by msqr1** [comment]
@tdcook Can you recheck (latest commit on main)?

**Comment by tdcook** [comment]
Looks good, thanks!
