### ISSUE TITLE
attention new error

### ISSUE THREAD

**Issue by twihorses** [msqr1/Vosklet#9]
Since yesterday this error occurred in everything, from examples to developments, I have gotten into several devices and it doesn't matter : 
vosk/:43 Uncaught (in promise) Untar: Incorrect tar format, must be USTAR
start @ vosk/:43
await in start (asíncrono)
onclick @ vosk/:46
Vosklet.js:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dispatchEvent')
    at 187996 (Vosklet.js:9:3446665)
    at Sg (Vosklet.js:9:3495122)
    at 009d28e2:0x1dc524
    at 009d28e2:0x1dc3ef
    at 009d28e2:0x1dc4ee
    at 009d28e2:0x93a39
    at 009d28e2:0x1dc054
    at 009d28e2:0x93a39
    at 009d28e2:0x1dbc8a
    at Fg (Vosklet.js:9:3493832)

**Comment by msqr1** [comment]
You should check if your tar format is USTAR or not, ie. Check the magic bytes. It's just ustar that works
